/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.HealthConsultantRole;

import Business.EcoSystem;
import Business.Enterprise.ConsultationEnterprise;
import Business.Enterprise.EcommerceEnterprise;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.HealthConsultationOrganization;
import Business.Organization.Organization;
import Business.Organization.WellnessPlatformOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.PharmacyWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import Business.Organization.PharmaOrganization;
import javax.swing.JPanel;
import Business.DB4OUtil.DB4OUtil;
import java.awt.CardLayout;
import java.awt.Component;
import userinterface.UserRole.UserWorkAreaJPanel;

/**
 *
 * @author ram
 */
public class HealthConsultantPharmaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form HealthConsultantPharmaJPanel
     */
    JPanel userProcessContainer;
    private WellnessPlatformOrganization organization;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private  WellnessPlatformOrganization wellnessPlatformOrganization;
    private Network network;
    private EcoSystem system;
    private DB4OUtil db;
    
    private Organization hcOrganisation;
 

   //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    

    public HealthConsultantPharmaJPanel(JPanel userProcessContainer, UserAccount userAccount, WellnessPlatformOrganization wellnessPlatformOrganization, Enterprise enterprise, EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.wellnessPlatformOrganization= wellnessPlatformOrganization;
        this.enterprise = enterprise;
        this.network = network;
        this.system = system;
    }
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        medicineJTxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        quantityJTxt = new javax.swing.JTextField();
        reqPharma = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(153, 204, 255));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel1.setText("Medicine:");

        medicineJTxt.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        medicineJTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medicineJTxtActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel2.setText("Quantity: ");

        quantityJTxt.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        quantityJTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantityJTxtActionPerformed(evt);
            }
        });

        reqPharma.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        reqPharma.setText("Send order to Pharma");
        reqPharma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reqPharmaActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButton1.setText("<< Back ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setText("Enter the Details for Pharmacy Request");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(medicineJTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                            .addComponent(quantityJTxt)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(89, 89, 89)
                        .addComponent(reqPharma, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 76, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(247, 247, 247))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(medicineJTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(quantityJTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(reqPharma, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(165, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void reqPharmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reqPharmaActionPerformed
        // TODO add your handling code here:
        PharmacyWorkRequest phar= new PharmacyWorkRequest();
         if(medicineJTxt.getText().trim().equals("") && quantityJTxt.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null, "please enter the prescription");
            return;
        }
        
        phar.setMedicationName(medicineJTxt.getText().trim());
        phar.setQuantity(Integer.parseInt(quantityJTxt.getText().trim())); // added username and HeartBeat 
        phar.setSender(userAccount);
        phar.setStatus("Medicine Requested!!");
        
        //get Doctor Org 
        Organization org = null;
        
        for (Network network : system.getNetworkList()) {
            for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
                if (enterprise instanceof EcommerceEnterprise) {
                    for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
                        if (organization instanceof PharmaOrganization) {  // change to pharma organisation .. 
                            org = organization;
                            System.out.println("healtc "+org.getName());
                            break;
                        }
                    }
                }

            }
        }
        
        System.out.println("Organisation is "+org.getName());

        if (org!= null) {
            org.getWorkQueue().getWorkRequestList().add(phar);
           // userAccount.getWorkQueue().getWorkRequestList().add(phar); // add workqueue to org 

            JOptionPane.showMessageDialog(null, "your prescription has beenr requested to pharma", "Information", JOptionPane.INFORMATION_MESSAGE);
        }
        System.out.println(org.getWorkQueue().getWorkRequestList().size());
//        db.storeSystem(system);

        for(WorkRequest w: org.getWorkQueue().getWorkRequestList()){
            PharmacyWorkRequest pw = (PharmacyWorkRequest)w;
            System.out.println("phar req inside"+pw.getMedicationName());
        }     
        
    }//GEN-LAST:event_reqPharmaActionPerformed

    private void medicineJTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medicineJTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_medicineJTxtActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
           userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        HealthConsultantJPanel dw = (HealthConsultantJPanel) component;
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void quantityJTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantityJTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quantityJTxtActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField medicineJTxt;
    private javax.swing.JTextField quantityJTxt;
    private javax.swing.JButton reqPharma;
    // End of variables declaration//GEN-END:variables
}
