/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package userinterface.HealthConsultantRole;

import Business.EcoSystem;
import Business.Enterprise.ConsultationEnterprise;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.WellnessPlatformOrganization;
import Business.UserAccount.UserAccount;
import javax.swing.JPanel;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.HealthConsultationOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.PharmacyWorkRequest;
import Business.WorkQueue.UserDoctorWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import org.apache.log4j.Logger;
import userinterface.HealthConsultantRole.HealthConsultantJPanel;
import userinterface.UserRole.UserWorkAreaJPanel;

/**
 *
 * @author shreyasprasad
 */
public class HealthConsultantJPanel extends javax.swing.JPanel {

    
    /**
     * Creates new form UserJPanel
     */
    
    JPanel userProcessContainer;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private  WellnessPlatformOrganization wellnessPlatformOrganization;
    private HealthConsultationOrganization healthConsultationOrganization;
    private Network network;
    private EcoSystem system;
    
    private Organization hcOrganisation;
    

    public HealthConsultantJPanel(JPanel userProcessContainer, UserAccount account, HealthConsultationOrganization healthConsultationOrganization, Enterprise enterprise, EcoSystem system, Network network) {
        
        this.userProcessContainer = userProcessContainer;
        this.userAccount = account;
        this.healthConsultationOrganization= healthConsultationOrganization;
        this.enterprise = enterprise;
        this.network = network;
        this.system = system;
        network();
        initComponents();
        System.out.println("inside the health consultant panel ");
        
        populateTable();
    }
    
    public void network() {
        network.getName();

    }
    
    private void populateTable(){
        DefaultTableModel model = (DefaultTableModel)hcTable.getModel();
        
        for (Network network : system.getNetworkList()) {
            for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
                if (enterprise instanceof ConsultationEnterprise) {
                    for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
                        if (organization instanceof HealthConsultationOrganization) {
                            hcOrganisation = organization;
                            break;
                        }
                    }
                }

            }
        }
      
       model.setRowCount(0);
        for (WorkRequest reqQueue : hcOrganisation.getWorkQueue().getWorkRequestList()){
            UserDoctorWorkRequest hcWorkRequest = (UserDoctorWorkRequest)reqQueue;
            Object[] row = new Object[7];
            row[0]= hcWorkRequest;
            row[1] = hcWorkRequest.getHeartBeat();
            row[2] = hcWorkRequest.getUserName();
            row[3] = hcWorkRequest.getStatus();
            //row[4] = hcWorkRequest;
            model.addRow(row);
        }
    
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        studyCaseBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        hcTable = new javax.swing.JTable();
        assignMeBtn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        studyCaseBtn.setText("Study Case");
        studyCaseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studyCaseBtnActionPerformed(evt);
            }
        });

        jLabel1.setText("Welcome to doctor work area");

        hcTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Reviever "
            }
        ));
        jScrollPane1.setViewportView(hcTable);

        assignMeBtn.setText("Assign to Me");
        assignMeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignMeBtnActionPerformed(evt);
            }
        });

        jButton1.setText("<--Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(154, 154, 154)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 771, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(assignMeBtn)
                        .addGap(155, 155, 155)
                        .addComponent(studyCaseBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(101, 101, 101)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(assignMeBtn)
                    .addComponent(studyCaseBtn)
                    .addComponent(jButton1))
                .addContainerGap(168, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void studyCaseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studyCaseBtnActionPerformed
        // TODO add your handling code here:
        
        // select the work queue.
        int selectedHCRequest = hcTable.getSelectedRow();
        
         if(selectedHCRequest >= 0){
             
           UserDoctorWorkRequest HCPcrequest =(UserDoctorWorkRequest)hcTable.getValueAt(selectedHCRequest, 0);
           System.out.println("recevier from table "+HCPcrequest.getReceiver().getUsername());
           System.out.println("recevier User account "+userAccount.getUsername());
           if(HCPcrequest.getReceiver().getUsername().equalsIgnoreCase(userAccount.getUsername())){
                HCPcrequest.setStatus("prescription");
                HealthConsultantPharmaJPanel processWorkRequestJPanel = new HealthConsultantPharmaJPanel(userProcessContainer, userAccount, wellnessPlatformOrganization, enterprise, system);
                userProcessContainer.add("processWorkRequestJPanel", processWorkRequestJPanel);
                CardLayout layout = (CardLayout) userProcessContainer.getLayout();
                layout.next(userProcessContainer);
           }
           else{
               JOptionPane.showMessageDialog(null, "Person is selected by nother doctor");
           }
           
           
       }else{
           JOptionPane.showMessageDialog(null, "Please Select any row");
       }
        
        
        
    }//GEN-LAST:event_studyCaseBtnActionPerformed

    private void assignMeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignMeBtnActionPerformed
        // TODO add your handling code here:
        
        // allow assign only if the status is waiting.. else return 
        int selectedHCRequest = hcTable.getSelectedRow();
        
         if(selectedHCRequest >= 0){
             UserDoctorWorkRequest HCPcrequest =(UserDoctorWorkRequest)hcTable.getValueAt(selectedHCRequest, 0);
            String status = HCPcrequest.getStatus();
            if(status.equalsIgnoreCase("waiting")){ // positive case
                //System.out.println("you are assigned to "+this.userAccount.getUsername());
                HCPcrequest.setReceiver(userAccount);
                System.out.println("The receiver is "+HCPcrequest.getReceiver());
                HCPcrequest.setStatus("Assigned");   
            }
            else{
                JOptionPane.showMessageDialog(null, "Sorry, patient is already assigned. Please select another Person ");
                return;
            }
         }
         else{
             System.out.println("Please select a row");
         }
         
         
         // pupulate the fresh updated table 
         populateTable();
        
        
    }//GEN-LAST:event_assignMeBtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
     
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton assignMeBtn;
    private javax.swing.JTable hcTable;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton studyCaseBtn;
    // End of variables declaration//GEN-END:variables
}
