/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.UserRole;

import Business.EcoSystem;
import Business.Enterprise.ConsultationEnterprise;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.HealthConsultationOrganization;
import Business.Organization.Organization;
import Business.Organization.WellnessPlatformOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.UserDoctorWorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import org.apache.log4j.Logger;
import userinterface.UserRole.UserWorkAreaJPanel;
import Business.DB4OUtil.DB4OUtil;
import Business.WorkQueue.WorkRequest;
import java.util.ArrayList;


/**
 *
 * @author ram
 */
public class UserHealthConsultantRequestJPanel extends javax.swing.JPanel {
    
    JPanel userProcessContainer;
    private WellnessPlatformOrganization organization;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private  WellnessPlatformOrganization wellnessPlatformOrganization;
    private Network network;
    private EcoSystem system;
   
    private static Logger log = Logger.getLogger(UserWorkAreaJPanel.class);
    private static final String CLASS_NAME = UserWorkAreaJPanel.class.getName();

     private DB4OUtil db = DB4OUtil.getInstance();
    /**
     * Creates new form UserHealthRequestJPanel
     */
    public UserHealthConsultantRequestJPanel(JPanel userProcessContainer,UserAccount userAccount,Enterprise enterprise,WellnessPlatformOrganization organization,EcoSystem system,Network network) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.wellnessPlatformOrganization = wellnessPlatformOrganization;
        this.enterprise = enterprise;
        this.network = network;
        this.system = system;
        network();
    }
    
    public void network() {
        network.getName();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        userNameJTxtFld = new javax.swing.JTextField();
        heartBeatJTxtFld = new javax.swing.JTextField();
        docReqJButton = new javax.swing.JButton();
        backJButton = new javax.swing.JButton();
        userNameJTxtFld1 = new javax.swing.JTextField();
        heartBeatJTxtFld1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        heartBeatJTxtFld2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        heartBeatJTxtFld3 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(153, 204, 255));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel1.setText("Name:");

        jLabel2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel2.setText("BP:");

        userNameJTxtFld.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        userNameJTxtFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userNameJTxtFldActionPerformed(evt);
            }
        });

        heartBeatJTxtFld.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        heartBeatJTxtFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                heartBeatJTxtFldActionPerformed(evt);
            }
        });

        docReqJButton.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        docReqJButton.setText("Request Doctor Consultation");
        docReqJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                docReqJButtonActionPerformed(evt);
            }
        });

        backJButton.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        backJButton.setText("<< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        userNameJTxtFld1.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        userNameJTxtFld1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userNameJTxtFld1ActionPerformed(evt);
            }
        });

        heartBeatJTxtFld1.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        heartBeatJTxtFld1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                heartBeatJTxtFld1ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel3.setText("Respiration Rate:");

        jLabel4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel4.setText("Body Temp:");

        heartBeatJTxtFld2.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        heartBeatJTxtFld2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                heartBeatJTxtFld2ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel5.setText("Pulse Rate:");

        jLabel6.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Enter the Details");

        heartBeatJTxtFld3.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        heartBeatJTxtFld3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                heartBeatJTxtFld3ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel7.setText("Message:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(backJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63)
                        .addComponent(docReqJButton))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(63, 63, 63)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(heartBeatJTxtFld)
                                .addComponent(userNameJTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(heartBeatJTxtFld2, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(heartBeatJTxtFld1)
                                .addComponent(userNameJTxtFld1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(heartBeatJTxtFld3, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(173, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabel6)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addComponent(userNameJTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(heartBeatJTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3)
                    .addComponent(userNameJTxtFld1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(heartBeatJTxtFld1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(heartBeatJTxtFld2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(heartBeatJTxtFld3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(docReqJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(backJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(173, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void userNameJTxtFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userNameJTxtFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userNameJTxtFldActionPerformed

    private void heartBeatJTxtFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_heartBeatJTxtFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_heartBeatJTxtFldActionPerformed

    private void docReqJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_docReqJButtonActionPerformed
        // TODO add your handling code here:
        if(userNameJTxtFld.getText().trim().equals("") && heartBeatJTxtFld.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null, "please enter the name");
            return;
        }
        
        UserDoctorWorkRequest userHC = new UserDoctorWorkRequest();
        userHC.setUserName(userNameJTxtFld.getText().trim());
        System.out.println("ented username is "+userHC.getUserName());
        userHC.setHeartBeat(Integer.parseInt(heartBeatJTxtFld.getText().trim())); // added username and HeartBeat 
        userHC.setSender(userAccount);
        userHC.setStatus("waiting");
        
        //get Doctor Org 
        Organization org = null;
        
        for (Network network : system.getNetworkList()) {
            for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
                if (enterprise instanceof ConsultationEnterprise) {
                    for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
                        if (organization instanceof HealthConsultationOrganization) {
                            org = organization;
                            break;
                        }
                    }
                }

            }
        }
        
        System.out.println("Organisation is "+org.getName());

        if (org!= null) {
            org.getWorkQueue().getWorkRequestList().add(userHC);
            // add workqueue to org
            System.out.println("inside queue"+userHC.getUserName());
            userAccount.getWorkQueue().getWorkRequestList().add(userHC); // add workqueue to org 

            JOptionPane.showMessageDialog(null, "Your Request has been sent to Health Consultant. You will recieve an email once the request is ready to process", "Information", JOptionPane.INFORMATION_MESSAGE);
        }
        System.out.println(org.getWorkQueue().getWorkRequestList().size());
        db.storeSystem(system);
        ArrayList<WorkRequest> w = org.getWorkQueue().getWorkRequestList();
        
    }//GEN-LAST:event_docReqJButtonActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        UserWorkAreaJPanel dw = (UserWorkAreaJPanel) component;
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
        
    }//GEN-LAST:event_backJButtonActionPerformed

    private void userNameJTxtFld1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userNameJTxtFld1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userNameJTxtFld1ActionPerformed

    private void heartBeatJTxtFld1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_heartBeatJTxtFld1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_heartBeatJTxtFld1ActionPerformed

    private void heartBeatJTxtFld2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_heartBeatJTxtFld2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_heartBeatJTxtFld2ActionPerformed

    private void heartBeatJTxtFld3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_heartBeatJTxtFld3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_heartBeatJTxtFld3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JButton docReqJButton;
    private javax.swing.JTextField heartBeatJTxtFld;
    private javax.swing.JTextField heartBeatJTxtFld1;
    private javax.swing.JTextField heartBeatJTxtFld2;
    private javax.swing.JTextField heartBeatJTxtFld3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField userNameJTxtFld;
    private javax.swing.JTextField userNameJTxtFld1;
    // End of variables declaration//GEN-END:variables
}
