/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.SupplementManager;

import userinterface.Pharmacist.*;
import Business.DB4OUtil.DB4OUtil;
import Business.EcoSystem;
import Business.Enterprise.EcommerceEnterprise;
import Business.Enterprise.Enterprise;
import Business.Enterprise.ManufacturingEnterprise;
import Business.Network.Network;
import Business.Organization.ManufacturingOrganization;
import Business.Organization.Organization;
import Business.Organization.PharmaOrganization;
import Business.Organization.WellnessPlatformOrganization;
import Business.Organization.FitnessConsultationOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.MfrWorkRequest;
import Business.WorkQueue.WorkRequest;
import javax.swing.JOptionPane;
import javax.swing.JPanel;



/**
 *
 * @author shwet
 */

   

public class ProcessOrderToMfrJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ProcessOrderToMfrJPanel
     */
    JPanel userProcessContainer;
    private PharmaOrganization pharmaOrganization;
    private FitnessConsultationOrganization fitnessConsultationOrganization;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private Network network;
    private EcoSystem system;
    private DB4OUtil db;
    private Organization Organisation;
    
               //ProcessOrderToMfrJPanel oTMFRJPanel = ProcessOrderToMfrJPanel(userProcessContainer,userAccount,pharmaOrganization,enterprise,ecosystem,network);
    public ProcessOrderToMfrJPanel(JPanel userProcessContainer, UserAccount account, FitnessConsultationOrganization fitnessConsultationOrganization, Enterprise enterprise, EcoSystem ecosystem, Network network){
        initComponents();

        this.userProcessContainer = userProcessContainer;
        this.userAccount = account;
        this.fitnessConsultationOrganization= fitnessConsultationOrganization;
        this.enterprise = enterprise;
        this.network= network;
        this.system = ecosystem;

       
   }   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnOrderToMfr = new javax.swing.JButton();
        txtMedicineName = new javax.swing.JTextField();
        txtQuantity = new javax.swing.JTextField();
        lblMedicineName = new javax.swing.JLabel();
        lblQuantity = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnOrderToMfr.setText("Order");
        btnOrderToMfr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrderToMfrActionPerformed(evt);
            }
        });
        add(btnOrderToMfr, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 270, -1, -1));
        add(txtMedicineName, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 100, 110, -1));
        add(txtQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 150, 110, -1));

        lblMedicineName.setText("Supp Name:");
        add(lblMedicineName, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, -1, -1));

        lblQuantity.setText("Quantity:");
        add(lblQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, -1, -1));

        jLabel1.setText("Request order to supp Manifacturer");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 310, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void btnOrderToMfrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrderToMfrActionPerformed
        // TODO add your handling code here:
        
        
        MfrWorkRequest manuRequest = new MfrWorkRequest();

        manuRequest.setMfrMedicine(txtMedicineName.getText());
        manuRequest.setMfrQuantity(Integer.parseInt(txtQuantity.getText()));
        manuRequest.setStatus("Ordered");
        System.out.println("manu button"+manuRequest.getStatus());

        Organization org = null;
        for (Network network : system.getNetworkList()) {
            

            for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {

                if (enterprise instanceof ManufacturingEnterprise) 
                {
                    System.out.println("In suppliment , entreprise"+enterprise.getName());

                    for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
                        if (organization instanceof FitnessConsultationOrganization) {
                            
                            org = organization;
                            System.out.println("In supp to , inside phars work request "+org.getName());
                            break;
                        }
                    }
                }
            }
        }
        //System.out.println("outside phars work request "+org.getName());
        if (org != null) {
            org.getWorkQueue().getWorkRequestList().add(manuRequest);
            userAccount.getWorkQueue().getWorkRequestList().add(manuRequest);

            JOptionPane.showMessageDialog(this, "Order Placed to supp Man!");
        }
    }//GEN-LAST:event_btnOrderToMfrActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOrderToMfr;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblMedicineName;
    private javax.swing.JLabel lblQuantity;
    private javax.swing.JTextField txtMedicineName;
    private javax.swing.JTextField txtQuantity;
    // End of variables declaration//GEN-END:variables
}
