/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package userinterface.SupplementManager;

import userinterface.Pharmacist.*;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.PharmaOrganization;
import Business.Organization.SupplementOrganization;
import Business.Organization.FitnessConsultationOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.FitSuppWorkRequest;
import Business.WorkQueue.MfrWorkRequest;
import Business.WorkQueue.PharmacyWorkRequest;
import Business.WorkQueue.WorkRequest;
import Business.WorkQueue.FitnessWorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import userinterface.ManufacturerRole.ProcessManuWorkRequest;

/**
 *
 * @author shreyasprasad
 */
public class SupplementManagerJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    //private PharmaOrganization pharmaOrganization;
    private FitnessConsultationOrganization fitnessConsultationOrganization;
    private SupplementOrganization supplementOrganization;
    
    private Enterprise enterprise;
    private UserAccount userAccount;
    private EcoSystem ecosystem;
    private Network network;
    
    
  

    public SupplementManagerJPanel(JPanel userProcessContainer, UserAccount account, SupplementOrganization supplementOrganization, Enterprise enterprise, EcoSystem ecosystem, Network network) {
           initComponents();
    
           
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = account;
        this.supplementOrganization= supplementOrganization;
        
        this.enterprise = enterprise;
        this.ecosystem = ecosystem;
        this.network= network;
        populateSupTable();
        
        
    }


       public void populateSupTable(){
           System.out.println("pupulating supp table");
       
        DefaultTableModel model = (DefaultTableModel) tblSupplimentOrder.getModel();
        model.setRowCount(0);
        
        for(WorkRequest request : supplementOrganization.getWorkQueue().getWorkRequestList()){
            Object[] row = new Object[5];
        FitSuppWorkRequest fitnessRequest = (FitSuppWorkRequest) request;
        row[0] = fitnessRequest;
        row[1] = fitnessRequest.getSuppName();
        row[2] = fitnessRequest.getSupQuantity();
        row[3] = fitnessRequest.getStatus();
        //row[2] = fitnessRequest.getStatus();
       
        model.addRow(row);
        }
         
       }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblSupplimentOrder = new javax.swing.JTable();
        btnProcess = new javax.swing.JButton();
        btnOrderToMfr = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblSupplimentOrder.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Supplement", "Quantity", "Sender", "Status"
            }
        ));
        jScrollPane1.setViewportView(tblSupplimentOrder);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, -1, 120));

        btnProcess.setText("Process");
        btnProcess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcessActionPerformed(evt);
            }
        });
        add(btnProcess, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 250, -1, -1));

        btnOrderToMfr.setText("Order");
        btnOrderToMfr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrderToMfrActionPerformed(evt);
            }
        });
        add(btnOrderToMfr, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 340, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnProcessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcessActionPerformed
        // TODO add your handling code here:
        
        int selectedRow = tblSupplimentOrder.getSelectedRow();

        if (selectedRow < 0){
            JOptionPane.showMessageDialog(this, "Please select a row to process this order");
            return;
        }
        FitSuppWorkRequest fitnessWR = (FitSuppWorkRequest) tblSupplimentOrder.getValueAt(selectedRow, 0);

        if(!fitnessWR.getStatus().equals("Requested")){ //change this status
            if(fitnessWR.getStatus().equals("Processing")){

                ProcessOrderWorkRequest processWorkRequestJPanel = new ProcessOrderWorkRequest(userProcessContainer, fitnessWR);
                userProcessContainer.add("processWorkRequestJPanel", processWorkRequestJPanel);
                CardLayout layout = (CardLayout) userProcessContainer.getLayout();
                layout.next(userProcessContainer);

            }
            else{
                JOptionPane.showMessageDialog(this, "This order has been processed before");
                return;
            }
        }

        fitnessWR.setStatus("Processing");

        ProcessOrderWorkRequest processWorkRequestJPanel = new ProcessOrderWorkRequest(userProcessContainer, fitnessWR);
        userProcessContainer.add("processWorkRequestJPanel", processWorkRequestJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnProcessActionPerformed
/**/
    private void btnOrderToMfrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrderToMfrActionPerformed
        // TODO add your handling code here:
        
        ProcessOrderToMfrJPanel oTMFRJPanel = new ProcessOrderToMfrJPanel(userProcessContainer,userAccount,fitnessConsultationOrganization,enterprise,ecosystem,network);
        userProcessContainer.add("manageNetworkJPanel",oTMFRJPanel);
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);        
    }//GEN-LAST:event_btnOrderToMfrActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOrderToMfr;
    private javax.swing.JButton btnProcess;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblSupplimentOrder;
    // End of variables declaration//GEN-END:variables

 


}
