/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.FitnessConsultationRole;

import userinterface.HealthConsultantRole.*;
import Business.EcoSystem;
import Business.Enterprise.ConsultationEnterprise;
import Business.Enterprise.EcommerceEnterprise;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.HealthConsultationOrganization;
import Business.Organization.Organization;
import Business.Organization.WellnessPlatformOrganization;
import Business.Organization.FitnessConsultationOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.PharmacyWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import Business.Organization.PharmaOrganization;
import Business.Organization.SupplementOrganization;
import javax.swing.JPanel;
import Business.DB4OUtil.DB4OUtil;
import java.awt.CardLayout;
import java.awt.Component;
import userinterface.UserRole.UserWorkAreaJPanel;
import Business.WorkQueue.FitSuppWorkRequest;

/**
 *
 * @author ram
 */
public class FitnessConsultantSupplementJPanel extends javax.swing.JPanel {

    /**
     * Creates new form HealthConsultantPharmaJPanel
     */
    JPanel userProcessContainer;
    private WellnessPlatformOrganization organization;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private  WellnessPlatformOrganization wellnessPlatformOrganization;
    private Network network;
    private EcoSystem system;
    private DB4OUtil db;
    
    private Organization hcOrganisation;
 

   //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    

    public FitnessConsultantSupplementJPanel(JPanel userProcessContainer, UserAccount userAccount, WellnessPlatformOrganization wellnessPlatformOrganization, Enterprise enterprise, EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.wellnessPlatformOrganization= wellnessPlatformOrganization;
        this.enterprise = enterprise;
        this.network = network;
        this.system = system;
    }
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        suppJTxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        quantityJTxt = new javax.swing.JTextField();
        reqSupp = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        jLabel1.setText("Suppliment Name");

        suppJTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suppJTxtActionPerformed(evt);
            }
        });

        jLabel2.setText("Quantity: ");

        quantityJTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantityJTxtActionPerformed(evt);
            }
        });

        reqSupp.setText("Place order to Suplement");
        reqSupp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reqSuppActionPerformed(evt);
            }
        });

        jButton1.setText("<--Back to Fitness Dashboard");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jButton1)
                        .addGap(44, 44, 44)
                        .addComponent(reqSupp, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(74, 74, 74)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(suppJTxt, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(quantityJTxt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(suppJTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(quantityJTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(reqSupp)
                    .addComponent(jButton1))
                .addContainerGap(140, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void reqSuppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reqSuppActionPerformed
        // TODO add your handling code here:
        FitSuppWorkRequest fsupreq= new FitSuppWorkRequest();
         if(suppJTxt.getText().trim().equals("") && quantityJTxt.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null, "please enter the Supplement");
            return;
        }
        
        fsupreq.setSuppName(suppJTxt.getText().trim());
        fsupreq.setSupQuantity(Integer.parseInt(quantityJTxt.getText().trim())); // added username and HeartBeat 
        fsupreq.setSender(userAccount);
        fsupreq.setStatus("requested");
        
        //get Doctor Org 
        Organization org = null;
        
        for (Network network : system.getNetworkList()) {
            for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
                if (enterprise instanceof EcommerceEnterprise) {
                    for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
                        if (organization instanceof SupplementOrganization) {  // change to Suppliment  organisation .. 
                            org = organization;
                            System.out.println("supplement "+org.getName());
                            break;
                        }
                    }
                }

            }
        }
        
        System.out.println("In Fitness, Organisation is "+org.getName());

        if (org!= null) {
            org.getWorkQueue().getWorkRequestList().add(fsupreq);
           // userAccount.getWorkQueue().getWorkRequestList().add(phar); // add workqueue to org 

            JOptionPane.showMessageDialog(null, "your prescription has been requested to Supplement", "Information", JOptionPane.INFORMATION_MESSAGE);
        }
        System.out.println(org.getWorkQueue().getWorkRequestList().size());
      // db.storeSystem(system);

        for(WorkRequest w: org.getWorkQueue().getWorkRequestList()){
            FitSuppWorkRequest pw = (FitSuppWorkRequest)w;
            System.out.println("supp req inside"+pw.getSuppMessage());
        }     
        
    }//GEN-LAST:event_reqSuppActionPerformed

    private void suppJTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suppJTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_suppJTxtActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
           userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        HealthConsultantJPanel dw = (HealthConsultantJPanel) component;
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void quantityJTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantityJTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quantityJTxtActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField quantityJTxt;
    private javax.swing.JButton reqSupp;
    private javax.swing.JTextField suppJTxt;
    // End of variables declaration//GEN-END:variables
}
