/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package userinterface.Pharmacist;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.PharmaOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.MfrWorkRequest;
import Business.WorkQueue.PharmacyWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import userinterface.ManufacturerRole.ProcessManuWorkRequest;

/**
 *
 * @author shreyasprasad
 */
public class PharmacistJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private PharmaOrganization pharmaOrganization;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private EcoSystem ecosystem;
    private Network network;
    
    
  

    public PharmacistJPanel(JPanel userProcessContainer, UserAccount account, PharmaOrganization pharmaOrganization, Enterprise enterprise, EcoSystem ecosystem, Network network) {
           initComponents();
    
           
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = account;
        this.pharmaOrganization = pharmaOrganization;
        this.enterprise = enterprise;
        this.ecosystem = ecosystem;
        this.network= network;
        populatePharmacyTable();
        
        
    }


       public void populatePharmacyTable(){
           System.out.println("populate pha table");
       
        DefaultTableModel model = (DefaultTableModel) tblPharmacyOrder.getModel();
        model.setRowCount(0);
        
        for(WorkRequest request : pharmaOrganization.getWorkQueue().getWorkRequestList()){
            Object[] row = new Object[6];
        PharmacyWorkRequest pharmaRequest = (PharmacyWorkRequest) request;
        row[0] = pharmaRequest;
        row[1] = pharmaRequest.getMedicationName();
        row[2] = pharmaRequest.getQuantity();
        row[3] = pharmaRequest.getSender();
        row[4] = pharmaRequest.getStatus();
        
       
        model.addRow(row);
        }
         
       }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblPharmacyOrder = new javax.swing.JTable();
        btnProcess = new javax.swing.JButton();
        btnOrderToMfr = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(153, 204, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblPharmacyOrder.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "re OJBJ", "Medicine ", "Quantity", "Sender", "Status"
            }
        ));
        jScrollPane1.setViewportView(tblPharmacyOrder);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, -1, 120));

        btnProcess.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        btnProcess.setText("Process");
        btnProcess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcessActionPerformed(evt);
            }
        });
        add(btnProcess, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 240, 150, 40));

        btnOrderToMfr.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        btnOrderToMfr.setText("Order");
        btnOrderToMfr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrderToMfrActionPerformed(evt);
            }
        });
        add(btnOrderToMfr, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 330, 130, 40));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Pharmacist Work Area");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 40, 450, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnProcessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcessActionPerformed
        // TODO add your handling code here:
        
        int selectedRow = tblPharmacyOrder.getSelectedRow();

        if (selectedRow < 0){
            JOptionPane.showMessageDialog(this, "Please select a row to process this order");
            return;
        }
        PharmacyWorkRequest pharmaRequest = (PharmacyWorkRequest) tblPharmacyOrder.getValueAt(selectedRow, 0);

        if(!pharmaRequest.getStatus().equals("Requested")){ //change this status
            if(pharmaRequest.getStatus().equals("Processing")){

                ProcessOrderWorkRequest processWorkRequestJPanel = new ProcessOrderWorkRequest(userProcessContainer, pharmaRequest);
                userProcessContainer.add("processWorkRequestJPanel", processWorkRequestJPanel);
                CardLayout layout = (CardLayout) userProcessContainer.getLayout();
                layout.next(userProcessContainer);

            }
            else{
                JOptionPane.showMessageDialog(this, "This order has been processed before");
                return;
            }
        }

        pharmaRequest.setStatus("Processing");

        ProcessOrderWorkRequest processWorkRequestJPanel = new ProcessOrderWorkRequest(userProcessContainer, pharmaRequest);
        userProcessContainer.add("processWorkRequestJPanel", processWorkRequestJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnProcessActionPerformed
/**/
    private void btnOrderToMfrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrderToMfrActionPerformed
        // TODO add your handling code here:
        
        ProcessOrderToMfrJPanel oTMFRJPanel = new ProcessOrderToMfrJPanel(userProcessContainer,userAccount,pharmaOrganization,enterprise,ecosystem,network);
        userProcessContainer.add("manageNetworkJPanel",oTMFRJPanel);
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);        
    }//GEN-LAST:event_btnOrderToMfrActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOrderToMfr;
    private javax.swing.JButton btnProcess;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPharmacyOrder;
    // End of variables declaration//GEN-END:variables

 


}
